// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: human_gen.proto

package grpc

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_human_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_human_gen_proto_rawDescGZIP(), []int{0}
}

func (x *Human) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Human) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadHumanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadHumanRequest) Reset() {
	*x = ReadHumanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadHumanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHumanRequest) ProtoMessage() {}

func (x *ReadHumanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHumanRequest.ProtoReflect.Descriptor instead.
func (*ReadHumanRequest) Descriptor() ([]byte, []int) {
	return file_human_gen_proto_rawDescGZIP(), []int{1}
}

func (x *ReadHumanRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ReadManyHumanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadManyHumanRequest) Reset() {
	*x = ReadManyHumanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadManyHumanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadManyHumanRequest) ProtoMessage() {}

func (x *ReadManyHumanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadManyHumanRequest.ProtoReflect.Descriptor instead.
func (*ReadManyHumanRequest) Descriptor() ([]byte, []int) {
	return file_human_gen_proto_rawDescGZIP(), []int{2}
}

func (x *ReadManyHumanRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ReadManyHumanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items *Human `protobuf:"bytes,1,opt,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ReadManyHumanResponse) Reset() {
	*x = ReadManyHumanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadManyHumanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadManyHumanResponse) ProtoMessage() {}

func (x *ReadManyHumanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_human_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadManyHumanResponse.ProtoReflect.Descriptor instead.
func (*ReadManyHumanResponse) Descriptor() ([]byte, []int) {
	return file_human_gen_proto_rawDescGZIP(), []int{3}
}

func (x *ReadManyHumanResponse) GetItems() *Human {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_human_gen_proto protoreflect.FileDescriptor

var file_human_gen_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2b, 0x0a, 0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x48, 0x75, 0x6d, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64,
	0x4d, 0x61, 0x6e, 0x79, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x3a, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x48, 0x75, 0x6d, 0x61,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x42, 0x0a, 0x0c,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09,
	0x52, 0x65, 0x61, 0x64, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_human_gen_proto_rawDescOnce sync.Once
	file_human_gen_proto_rawDescData = file_human_gen_proto_rawDesc
)

func file_human_gen_proto_rawDescGZIP() []byte {
	file_human_gen_proto_rawDescOnce.Do(func() {
		file_human_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_human_gen_proto_rawDescData)
	})
	return file_human_gen_proto_rawDescData
}

var file_human_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_human_gen_proto_goTypes = []interface{}{
	(*Human)(nil),                 // 0: grpc.Human
	(*ReadHumanRequest)(nil),      // 1: grpc.ReadHumanRequest
	(*ReadManyHumanRequest)(nil),  // 2: grpc.ReadManyHumanRequest
	(*ReadManyHumanResponse)(nil), // 3: grpc.ReadManyHumanResponse
}
var file_human_gen_proto_depIdxs = []int32{
	0, // 0: grpc.ReadManyHumanResponse.Items:type_name -> grpc.Human
	1, // 1: grpc.HumanService.ReadHuman:input_type -> grpc.ReadHumanRequest
	0, // 2: grpc.HumanService.ReadHuman:output_type -> grpc.Human
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_human_gen_proto_init() }
func file_human_gen_proto_init() {
	if File_human_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_human_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_human_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadHumanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_human_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadManyHumanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_human_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadManyHumanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_human_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_human_gen_proto_goTypes,
		DependencyIndexes: file_human_gen_proto_depIdxs,
		MessageInfos:      file_human_gen_proto_msgTypes,
	}.Build()
	File_human_gen_proto = out.File
	file_human_gen_proto_rawDesc = nil
	file_human_gen_proto_goTypes = nil
	file_human_gen_proto_depIdxs = nil
}
