// Code generated by config, DO NOT EDIT.
package config

import (
	"github.com/wheissd/mkgo/gen/config"
	"go.uber.org/fx"
)

var Module = fx.Module("services",
	fx.Provide(
		Init,
		GetAPI,

		GetGRPC,

		GetDB,
	),
	fx.Invoke(func(Config) {}),
)

var cfg Config

func Init() Config {
	config.Parse[*Config](&cfg)
	return cfg
}

func GetAPI() API {
	return cfg.API
}

func GetGRPC() GRPC {
	return cfg.GRPC
}

func GetDB() DB {
	return cfg.DB
}
