// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateHumanRes interface {
	createHumanRes()
}

type DeleteHumanRes interface {
	deleteHumanRes()
}

type ListHumanRes interface {
	listHumanRes()
}

type ReadHumanRes interface {
	readHumanRes()
}

type UpdateHumanRes interface {
	updateHumanRes()
}
