// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: default_model_gen.proto

package grpc

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DefaultModel) Reset() {
	*x = DefaultModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_model_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultModel) ProtoMessage() {}

func (x *DefaultModel) ProtoReflect() protoreflect.Message {
	mi := &file_default_model_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultModel.ProtoReflect.Descriptor instead.
func (*DefaultModel) Descriptor() ([]byte, []int) {
	return file_default_model_gen_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultModel) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DefaultModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadDefaultModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadDefaultModelRequest) Reset() {
	*x = ReadDefaultModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_model_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDefaultModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDefaultModelRequest) ProtoMessage() {}

func (x *ReadDefaultModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_default_model_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDefaultModelRequest.ProtoReflect.Descriptor instead.
func (*ReadDefaultModelRequest) Descriptor() ([]byte, []int) {
	return file_default_model_gen_proto_rawDescGZIP(), []int{1}
}

func (x *ReadDefaultModelRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ReadManyDefaultModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadManyDefaultModelRequest) Reset() {
	*x = ReadManyDefaultModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_model_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadManyDefaultModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadManyDefaultModelRequest) ProtoMessage() {}

func (x *ReadManyDefaultModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_default_model_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadManyDefaultModelRequest.ProtoReflect.Descriptor instead.
func (*ReadManyDefaultModelRequest) Descriptor() ([]byte, []int) {
	return file_default_model_gen_proto_rawDescGZIP(), []int{2}
}

func (x *ReadManyDefaultModelRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ReadManyDefaultModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items *DefaultModel `protobuf:"bytes,1,opt,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ReadManyDefaultModelResponse) Reset() {
	*x = ReadManyDefaultModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_default_model_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadManyDefaultModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadManyDefaultModelResponse) ProtoMessage() {}

func (x *ReadManyDefaultModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_default_model_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadManyDefaultModelResponse.ProtoReflect.Descriptor instead.
func (*ReadManyDefaultModelResponse) Descriptor() ([]byte, []int) {
	return file_default_model_gen_proto_rawDescGZIP(), []int{3}
}

func (x *ReadManyDefaultModelResponse) GetItems() *DefaultModel {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_default_model_gen_proto protoreflect.FileDescriptor

var file_default_model_gen_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x32, 0x0a, 0x0c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2d,
	0x0a, 0x1b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x48, 0x0a,
	0x1c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x5e, 0x0a, 0x13, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47,
	0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_default_model_gen_proto_rawDescOnce sync.Once
	file_default_model_gen_proto_rawDescData = file_default_model_gen_proto_rawDesc
)

func file_default_model_gen_proto_rawDescGZIP() []byte {
	file_default_model_gen_proto_rawDescOnce.Do(func() {
		file_default_model_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_default_model_gen_proto_rawDescData)
	})
	return file_default_model_gen_proto_rawDescData
}

var file_default_model_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_default_model_gen_proto_goTypes = []interface{}{
	(*DefaultModel)(nil),                 // 0: grpc.DefaultModel
	(*ReadDefaultModelRequest)(nil),      // 1: grpc.ReadDefaultModelRequest
	(*ReadManyDefaultModelRequest)(nil),  // 2: grpc.ReadManyDefaultModelRequest
	(*ReadManyDefaultModelResponse)(nil), // 3: grpc.ReadManyDefaultModelResponse
}
var file_default_model_gen_proto_depIdxs = []int32{
	0, // 0: grpc.ReadManyDefaultModelResponse.Items:type_name -> grpc.DefaultModel
	1, // 1: grpc.DefaultModelService.ReadDefaultModel:input_type -> grpc.ReadDefaultModelRequest
	0, // 2: grpc.DefaultModelService.ReadDefaultModel:output_type -> grpc.DefaultModel
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_default_model_gen_proto_init() }
func file_default_model_gen_proto_init() {
	if File_default_model_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_default_model_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_default_model_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDefaultModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_default_model_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadManyDefaultModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_default_model_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadManyDefaultModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_default_model_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_default_model_gen_proto_goTypes,
		DependencyIndexes: file_default_model_gen_proto_depIdxs,
		MessageInfos:      file_default_model_gen_proto_msgTypes,
	}.Build()
	File_default_model_gen_proto = out.File
	file_default_model_gen_proto_rawDesc = nil
	file_default_model_gen_proto_goTypes = nil
	file_default_model_gen_proto_depIdxs = nil
}
