// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: default_model_gen.proto

package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DefaultModelService_ReadDefaultModel_FullMethodName = "/grpc.DefaultModelService/ReadDefaultModel"
)

// DefaultModelServiceClient is the client API for DefaultModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DefaultModelServiceClient interface {
	ReadDefaultModel(ctx context.Context, in *ReadDefaultModelRequest, opts ...grpc.CallOption) (*DefaultModel, error)
}

type defaultModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultModelServiceClient(cc grpc.ClientConnInterface) DefaultModelServiceClient {
	return &defaultModelServiceClient{cc}
}

func (c *defaultModelServiceClient) ReadDefaultModel(ctx context.Context, in *ReadDefaultModelRequest, opts ...grpc.CallOption) (*DefaultModel, error) {
	out := new(DefaultModel)
	err := c.cc.Invoke(ctx, DefaultModelService_ReadDefaultModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultModelServiceServer is the server API for DefaultModelService service.
// All implementations must embed UnimplementedDefaultModelServiceServer
// for forward compatibility
type DefaultModelServiceServer interface {
	ReadDefaultModel(context.Context, *ReadDefaultModelRequest) (*DefaultModel, error)
	mustEmbedUnimplementedDefaultModelServiceServer()
}

// UnimplementedDefaultModelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDefaultModelServiceServer struct {
}

func (UnimplementedDefaultModelServiceServer) ReadDefaultModel(context.Context, *ReadDefaultModelRequest) (*DefaultModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDefaultModel not implemented")
}
func (UnimplementedDefaultModelServiceServer) mustEmbedUnimplementedDefaultModelServiceServer() {}

// UnsafeDefaultModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefaultModelServiceServer will
// result in compilation errors.
type UnsafeDefaultModelServiceServer interface {
	mustEmbedUnimplementedDefaultModelServiceServer()
}

func RegisterDefaultModelServiceServer(s grpc.ServiceRegistrar, srv DefaultModelServiceServer) {
	s.RegisterService(&DefaultModelService_ServiceDesc, srv)
}

func _DefaultModelService_ReadDefaultModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDefaultModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultModelServiceServer).ReadDefaultModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultModelService_ReadDefaultModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultModelServiceServer).ReadDefaultModel(ctx, req.(*ReadDefaultModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DefaultModelService_ServiceDesc is the grpc.ServiceDesc for DefaultModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DefaultModelService",
	HandlerType: (*DefaultModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadDefaultModel",
			Handler:    _DefaultModelService_ReadDefaultModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "default_model_gen.proto",
}
