// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListDefaultModel implements listDefaultModel operation.
	//
	// List for DefaultModels.
	//
	// GET /defaultmodel
	ListDefaultModel(ctx context.Context, params ListDefaultModelParams) (ListDefaultModelRes, error)
	// ReadDefaultModel implements readDefaultModel operation.
	//
	// Finds the DefaultModel with the requested ID and returns it.
	//
	// GET /defaultmodel/{id}
	ReadDefaultModel(ctx context.Context, params ReadDefaultModelParams) (ReadDefaultModelRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
