// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListDefaultModel implements listDefaultModel operation.
//
// List for DefaultModels.
//
// GET /defaultmodel
func (UnimplementedHandler) ListDefaultModel(ctx context.Context, params ListDefaultModelParams) (r ListDefaultModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadDefaultModel implements readDefaultModel operation.
//
// Finds the DefaultModel with the requested ID and returns it.
//
// GET /defaultmodel/{id}
func (UnimplementedHandler) ReadDefaultModel(ctx context.Context, params ReadDefaultModelParams) (r ReadDefaultModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
